## Numpy

## pip intall numpy

In [ ]:
pip install numpy

In [ ]:
import numpy as np

## create array using numpy 

## create a 1D array

arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

In [1]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.2 -> 26.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
pip install --upgrade pip

Defaulting to user installation because normal site-packages is not writeable
  Using cached pip-26.0-py3-none-any.whl.metadata (4.7 kB)
Using cached pip-26.0-py3-none-any.whl (1.8 MB)
Note: you may need to restart the kernel to use updated packages.


In [ ]:
import numpy as np

## create array using numpy 

## create a 1D array

arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape) ## tell the dimension

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [ ]:
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5)   ## reshaped to 2d array having 1 row and 5 columns 



array([[1, 2, 3, 4, 5]])

In [5]:
## using the nested array

arr2=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr2)
print(arr2.shape)  ## havig 2 rows and 5 elements


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(2, 5)


In [ ]:
np.arange(0,10,2).reshape(5,1)  ## 0 to 10 with 2 gap in shape of 5 row and 1 col



array([[0],
       [2],
       [4],
       [6],
       [8]])

In [ ]:
np.ones((3,4))  ## all ones 

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
## identity matrix 

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
## write the attributes of the array 


In [ ]:
## Numpy vectorised operation 
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

## done element by element on indexing 

## element wise addition 

print("Addition: " ,arr1+arr2)
## subtraction
print("Addition: " ,arr1-arr2)
print("Addition: " ,arr1*arr2)
print("Addition: " ,arr1/arr2)


Addition:  [11 22 33 44 55]


In [12]:
## universal function 

arr=np.array([1,2,3,4,5])
## square root 
print(np.sqrt(arr))
print(np.exp(arr))
print(np.sin(arr))
print(np.log(arr))

[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [23]:
## array slicing and indexing 

arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array: " , arr)

Array:  [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
## accessing the element 

print(arr[0][0])
print(arr[1:])
print(arr[1:,2:])  ## get all elements from 2 row and their elements after the 2 index 

print(arr[0:2,2:])  ## will go from the 0 to 1 row and give element from 3 to last 

1
[[ 5  6  7  8]
 [ 9 10 11 12]]
[[ 7  8]
 [11 12]]
[[3 4]
 [7 8]]


In [29]:
## modify 
arr[0,0]=100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [30]:
arr[1:]=100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [31]:
## statistical concepts-normalisation 
## to have a mean of 0 and standarad deviation of 1 

## mean mode median std var(variance) 

In [35]:
## logical operations (pandas) 
data=np.array([1,2,3,4,5,6,7,8,9,10])
data>5  ## give boolean array
data[(data>=5) & (data<=8)]  ## can use and or not 

array([5, 6, 7, 8])

## Pandas

## used for data analysis and cleaning of the data 

In [36]:
pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [1]:
import pandas as pd 


In [4]:
## pandas series 

import pandas as pd
data=[1,2,3,4,5]
series=pd.Series(data)
print("Series: \n",series)
print(type(series))

Series: 
 0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.Series'>


In [6]:
## create the series from dictionary 
data={'a':1,'b':2,'c':3}
series_dict=pd.Series(data)
print(series_dict)

a    1
b    2
c    3
dtype: int64


In [7]:
## imp for manipulation of data
data=[10,20,30]
index=['a','b','c']
pd.Series(data,index=index)

a    10
b    20
c    30
dtype: int64

In [9]:
## Data frame 
## create a database from a dictionary of list 

data={
    'Name':['Osheen','Anurag','Manoj'],
    "Age":[20,22,20],
    "City":['Idk1','idk2','idk3']
}
df=pd.DataFrame(data)
print(df)
print(type(df))
## can use numpy but created as array 

     Name  Age  City
0  Osheen   20  Idk1
1  Anurag   22  idk2
2   Manoj   20  idk3
<class 'pandas.DataFrame'>


In [36]:
## create a data frame from alist of dictionaries 
data=[
    {'Name':"Osheen",'age':20,"City":'Idk'},
    {'Name':"Anurag",'age':21,"City":'Idk1'},
    {'Name':"Manoj",'age':22,"City":'Idk2'},
    {'Name':"Osheen1",'age':23,"City":'Idk3'}
]
df = pd.DataFrame(data)
print(df)
print(type(df))

      Name  age  City
0   Osheen   20   Idk
1   Anurag   21  Idk1
2    Manoj   22  Idk2
3  Osheen1   23  Idk3
<class 'pandas.DataFrame'>


In [ ]:
## for csv file 
df=pd.read_csv('Students_data.csv')
print(df.head(5))  ## give first 5 row of data 
print(df.tail(5))  ## give last 5 


     ID class  gender  race    GPA  Algebra  Calculus1  Calculus2  Statistics  \
0  1141     A    male     1  73.47       64         81         87          60   
1  1142     A  female     1  71.22       57         50         51          51   
2  1143     A  female     2  74.56       47         48         71          60   
3  1144     A  female     1  72.89       46         72         38          60   
4  1145     A  female     1  70.11       49         45         63          60   

   Probability  Measure  Functional_analysis from1 from2 from3  from4  y  
0           74       71                   60     A     A     A      3  0  
1           55       62                   61     B     A     A      2  0  
2           61       68                   64     C     A     A      0  1  
3           29       54                   51     D     A     A      0  0  
4           66       66                   61     E     A     A      0  0  
       ID class  gender  race    GPA  Algebra  Calculus1  Calcu

In [ ]:
## accessing data from the data frame 
# df['Name']
# type(df['Name'])

# df.loc[0]  ## zeroth element   ## level based means give the columns name 
df.iloc[0,1]   ## indexed based element 

np.int64(20)

In [ ]:
## accessing specified element 
# df['Name']
# df

df.at[1,'age']  # first index age 

np.int64(21)

In [47]:
## accessing specified element using iat 
df.iat[2,2]  ## work by indexing 

'Idk2'

In [48]:
## data manipulation with data frames 

df

Name  age  City
0   Osheen   20   Idk
1   Anurag   21  Idk1
2    Manoj   22  Idk2
3  Osheen1   23  Idk3

In [63]:
df['Salary']=[50000,60056,632645,54646]
df

Name  age  City  Salary
0   Osheen   20   Idk   50000
1   Anurag   21  Idk1   60056
2    Manoj   22  Idk2  632645
3  Osheen1   23  Idk3   54646

In [64]:
df.drop('Salary',axis=1)   ## temporary
df



Name  age  City  Salary
0   Osheen   20   Idk   50000
1   Anurag   21  Idk1   60056
2    Manoj   22  Idk2  632645
3  Osheen1   23  Idk3   54646

In [65]:
## to do permanent 
df.drop('Salary',axis=1 ,inplace=True)
df

Name  age  City
0   Osheen   20   Idk
1   Anurag   21  Idk1
2    Manoj   22  Idk2
3  Osheen1   23  Idk3

In [67]:
## add age to column 
df['age']=df['age']+1
df

Name  age  City
0   Osheen   22   Idk
1   Anurag   23  Idk1
2    Manoj   24  Idk2
3  Osheen1   25  Idk3

In [70]:
## drop 
df.drop(0,inplace=True)


KeyError: '[0] not found in axis'

In [71]:
df

Name  age  City
1   Anurag   23  Idk1
2    Manoj   24  Idk2
3  Osheen1   25  Idk3

In [ ]:
df.describe() ## describe the data with info of operation that can be done on it 

age
count   3.0
mean   24.0
std     1.0
min    23.0
25%    23.5
50%    24.0
75%    24.5
max    25.0